// ==========================================
// БАЗА ДАНИХ АВТОМОБІЛІВ ТА КАТЕГОРІЙ (cars.js)
// ==========================================

const VEHICLE_CATEGORIES = {
    PASSENGER: "Легкові автомобілі",
    TRUCK: "Вантажні автомобілі",
    SUV: "Позашляховики",
    MINIBUS: "Мікроавтобуси",
    ADBLUE: "Автомобілі з AdBlue",
    MILES: "Автомобілі з милями",
    HQ: "Штабні автомобілі",
    SPECIAL: "Спецтехніка",
    MOTORCYCLE: "Мотоцикли",
    QUAD: "Квадроцикли"
};

let carsData = [
    {
        id: 1,
        plate: "KI 100 G",
        model: "Skoda Octavia",
        subdivision: "РМТЗ",
        consumption: 7.5,
        fuelType: "ДП",
        note: "Основний",
        vin: "TMBJJ7NE0J0123456",
        year: 2018,
        transmission: "механіка",
        tankCapacity: 50,
        drive: "передній",
        emptyWeight: 1250,
        totalWeight: 1800,
        gears: 6,
        engineVolume: 1968,
        kw: 110,
        engineNo: "CKFB123",
        driver: "Сидоренко С.С.",
        category: "passenger",
        vehicleType: "легковий",
        hasAdBlue: false,
        isMiles: false,
        formulas: [1, 2, 3, 4]
    },
    {
        id: 2,
        plate: "АІ 487 G",
        model: "Renault D14 HIGH P4*4 280 E3",
        subdivision: "РМТЗ",
        consumption: 25.0,
        fuelType: "ДП",
        note: "Резерв",
        vin: "VF640K831PB000231",
        year: 2022,
        transmission: "механіка",
        tankCapacity: 200,
        drive: "Задній, повний ручний",
        emptyWeight: 7500,
        totalWeight: 14000,
        gears: 6,
        engineVolume: 7698,
        kw: 210,
        engineNo: "22625483-4201027G22AXW",
        driver: "Іванов І.І.",
        category: "truck",
        vehicleType: "вантажний",
        hasAdBlue: false,
        isMiles: false,
        formulas: [5, 2, 3, 6]
    },
    {
        id: 3,
        plate: "TІ 666 G",
        model: "MAN TGS 33.400 6x6",
        subdivision: "РМТЗ",
        consumption: 32.3,
        fuelType: "ДП",
        note: "Вантажний з AdBlue",
        vin: "Y69SKS334R0C18170",
        year: 2024,
        transmission: "автомат",
        tankCapacity: 400,
        drive: "3 мости задн. Повний ручний",
        emptyWeight: 14200,
        totalWeight: 31000,
        gears: 0,
        engineVolume: 10518,
        kw: 294,
        engineNo: "5101101-3401",
        driver: "Водій / Старший водій",
        category: "truck",
        vehicleType: "вантажний",
        hasAdBlue: true,
        isMiles: false,
        formulas: [5, 1, 2, 3, 6, 7]
    },
    {
        id: 4,
        plate: "КІ 103 G",
        model: "Ford Explorer (US)",
        subdivision: "РМТЗ",
        consumption: 14.0,
        fuelType: "АБ",
        note: "Американська версія (милі)",
        vin: "1FM5K8F8LGA123789",
        year: 2016,
        transmission: "автомат",
        tankCapacity: 70,
        drive: "повний",
        emptyWeight: 2100,
        totalWeight: 2850,
        gears: 6,
        engineVolume: 3496,
        kw: 213,
        engineNo: "US35V6",
        driver: "Коваленко К.К.",
        category: "miles",
        vehicleType: "легковий",
        hasAdBlue: false,
        isMiles: true,
        formulas: [1, 2, 3, 4]
    },
    {
        id: 5,
        plate: "КІ 104 G",
        model: "TOYOTA LAND CRUISER",
        subdivision: "БПЛА",
        consumption: 12.5,
        fuelType: "АБ",
        note: "Штабний з AdBlue",
        vin: "JTEBZ22J30K987654",
        year: 2021,
        transmission: "автомат",
        tankCapacity: 93,
        drive: "повний",
        emptyWeight: 2450,
        totalWeight: 3260,
        gears: 6,
        engineVolume: 3346,
        kw: 227,
        engineNo: "F33A-FTV",
        driver: "Петров П.П.",
        category: "adblue",
        vehicleType: "вантажний",
        hasAdBlue: true,
        isMiles: false,
        formulas: [5, 1, 2, 3, 6, 7]
    },
    {
        id: 6,
        plate: "КІ 105 G",
        model: "Ford Explorer (US)",
        subdivision: "БПЛА",
        consumption: 14.0,
        fuelType: "АБ",
        note: "Американська версія (милі)",
        vin: "1FM5K8F8LGA123456",
        year: 2016,
        transmission: "автомат",
        tankCapacity: 70,
        drive: "повний",
        emptyWeight: 2100,
        totalWeight: 2850,
        gears: 6,
        engineVolume: 3496,
        kw: 213,
        engineNo: "US35V6",
        driver: "Мельник М.М.",
        category: "miles",
        vehicleType: "легковий",
        hasAdBlue: false,
        isMiles: true,
        formulas: [1, 2, 3, 4]
    },
    {
        id: 7,
        plate: "КІ 106 G",
        model: "Toyota Camry",
        subdivision: "БПЛА",
        consumption: 8.5,
        fuelType: "АБ",
        note: "Штабний",
        vin: "4T1B11HK5JU987654",
        year: 2020,
        transmission: "автомат",
        tankCapacity: 60,
        drive: "передній",
        emptyWeight: 1550,
        totalWeight: 2100,
        gears: 8,
        engineVolume: 2487,
        kw: 151,
        engineNo: "A25AFKS",
        driver: "Командувач",
        category: "hq",
        vehicleType: "легковий",
        hasAdBlue: false,
        isMiles: false,
        formulas: [1, 2, 3, 4]
    },
    {
        id: 8,
        plate: "КІ 107 G",
        model: "MAN TGS (Евакуатор)",
        subdivision: "ВТО",
        consumption: 25.0,
        fuelType: "ДП",
        note: "Спецтехніка важка",
        vin: "WMA13XZZ5MW123456",
        year: 2019,
        transmission: "механіка",
        tankCapacity: 300,
        drive: "повний",
        emptyWeight: 11000,
        totalWeight: 26000,
        gears: 16,
        engineVolume: 12419,
        kw: 353,
        engineNo: "D2676LF",
        driver: "Технік Т.Т.",
        category: "special",
        vehicleType: "вантажний",
        hasAdBlue: true,
        isMiles: false,
        formulas: [5, 1, 2, 3, 6, 7]
    },
    {
        id: 9,
        plate: "ТІ 102 G",
        model: "MAN TGM13.320 ВВ СН 4*4",
        subdivision: "ВТО",
        consumption: 21.5,
        fuelType: "ДП",
        note: "Вантажний з AdBlue",
        vin: "1J8G2E8A54Y140225",
        year: 2004,
        transmission: "автомат",
        tankCapacity: 78,
        drive: "повний",
        emptyWeight: 2260,
        totalWeight: 2750,
        gears: 5,
        engineVolume: 2987,
        kw: 160,
        engineNo: "—",
        driver: "Водій / Старший водій",
        category: "truck",
        vehicleType: "вантажний",
        hasAdBlue: true,
        isMiles: false,
        formulas: [5, 1, 2, 3, 6, 7]
    },
    {
        id: 10,
        plate: "ТІ 254 G",
        model: "Suzuki GSX250R",
        subdivision: "РМТЗ",
        consumption: 3.5,
        fuelType: "ДП",
        note: "",
        vin: "WMA13XZZ5",
        year: 2020,
        transmission: "автомат",
        tankCapacity: 15,
        drive: "задній",
        emptyWeight: 178,
        totalWeight: 250,
        gears: 6,
        engineVolume: 248,
        kw: 40,
        engineNo: "12452",
        driver: "водій",
        category: "motorcycle",
        vehicleType: "мотоцикл",
        hasAdBlue: false,
        isMiles: false,
        formulas: [8, 9]
    },
    {
        id: 11,
        plate: "ТІ 255 G",
        model: "CFORCE 1000 MV",
        subdivision: "РМТЗ",
        consumption: 9.0,
        fuelType: "ДП",
        note: "",
        vin: "WMA13XZZ5",
        year: 2020,
        transmission: "автомат",
        tankCapacity: 15,
        drive: "задній",
        emptyWeight: 178,
        totalWeight: 250,
        gears: 6,
        engineVolume: 248,
        kw: 40,
        engineNo: "12452",
        driver: "водій",
        category: "quad",
        vehicleType: "квадроцикл",
        hasAdBlue: false,
        isMiles: false,
        formulas: [8, 9]
    },
    {
        id: 12,
        plate: "ТІ 255 G",
        model: "CFORCE 1000 MV",
        subdivision: "РМТЗ",
        consumption: 9.0,
        fuelType: "ДП",
        note: "",
        vin: "WMA13XZZ5",
        year: 2020,
        transmission: "автомат",
        tankCapacity: 15,
        drive: "задній",
        emptyWeight: 178,
        totalWeight: 250,
        gears: 6,
        engineVolume: 248,
        kw: 40,
        engineNo: "12452",
        driver: "водій",
        category: "quad",
        vehicleType: "квадроцикл",
        hasAdBlue: false,
        isMiles: false,
        formulas: [8, 9]
    },
    {
        id: 13,
        plate: "TІ 659 G",
        model: "MAN TGS 33.400 6x6",
        subdivision: "РМТЗ",
        consumption: 32.3,
        fuelType: "ДП",
        note: "Вантажний з AdBlue",
        vin: "Y69SKS334R0C18170",
        year: 2024,
        transmission: "автомат",
        tankCapacity: 400,
        drive: "3 мости задн. Повний ручний",
        emptyWeight: 14200,
        totalWeight: 31000,
        gears: 0,
        engineVolume: 10518,
        kw: 294,
        engineNo: "5101101-3401",
        driver: "Водій / Старший водій",
        category: "truck",
        vehicleType: "вантажний",
        hasAdBlue: true,
        isMiles: false,
        formulas: [5, 1, 2, 3, 6, 7]
    }
];

// Функція постійного збереження бази в пам'ять браузера
function saveCarsToStorage() {
    try {
        localStorage.setItem('user_cars_database_v2', JSON.stringify(carsData));
    } catch (e) {
        console.error("Помилка збереження даних:", e);
    }
}

// Автоматичне завантаження збереженої бази при запуску сторінки
(function loadCarsFromStorage() {
    try {
        const saved = localStorage.getItem('user_cars_database_v2');
        if (saved) {
            const parsed = JSON.parse(saved);
            if (Array.isArray(parsed) && parsed.length > 0) {
                carsData = parsed;
            }
        }
    } catch (e) {
        console.error("Помилка завантаження даних:", e);
    }
})();