// ==========================================
// БАЗА ДАНИХ АВТОМОБІЛІВ ТА КАТЕГОРІЙ
// ==========================================

const VEHICLE_CATEGORIES = {
    PASSENGER: "Легкові автомобілі",
    TRUCK: "Вантажні автомобілі",
    SUV: "Позашляховики",
    MINIBUS: "Мікроавтобуси",
    ADBLUE: "Автомобілі з AdBlue",
    MILES: "Автомобілі з милями",
    HQ: "Штабні автомобілі",
    SPECIAL: "Спецтехніка",
    MOTORCYCLE: "Мотоцикли",
    QUAD: "Квадроцикли"
};

let carsData = [
    {
        id: 1,                          // Унікальний ідентифікаційний номер автомобіля в системі
        plate: "KI 100 G",              // Реєстраційний номер (номерний знак) транспортного засобу
        model: "Skoda Octavia",         // Марка та модель транспортного засобу
        subdivision: "PMT3",            // Підрозділ або рота, за якою закріплений даний транспортний засіб
        consumption: 7.5,               // Базова норма витрати палива (у літрах на 100 км пробігу)
        fuelType: "ДП",                 // Тип пального (наприклад, дизельне паливо — ДП)
        note: "Основний",               // Додаткова примітка або статус транспортного засобу
        vin: "TMBJJ7NE0J0123456",       // Унікальний VIN-код (номер кузова/шасі) автомобіля
        year: 2018,                     // Рік випуску транспортного засобу
        transmission: "механіка",       // Тип коробки перемикання передач (механіка, автомат тощо)
        tankCapacity: 50,               // Місткість паливного бака автомобіля у літрах
        drive: "передній",              // Тип приводу транспортного засобу (передній, задній, повний)
        emptyWeight: 1250,              // Маса автомобіля без навантаження (споряджена маса) у кілограмах
        totalWeight: 1800,              // Повна допустима маса транспортного засобу у кілограмах
        gears: 6,                       // Кількість передач у коробці перемикання передач
        engineVolume: 1968,             // Робочий об'єм двигуна у кубічних сантиметрах (см³)
        kw: 110,                        // Потужність двигуна в кіловатах (кВт)
        engineNo: "CKFB123",            // Заводський номер двигуна
        driver: "Сидоренко С.С.",       // Прізвище та ініціали закріпленого водія або старшого водія
        category: "passenger",          // Категорія транспортного засобу в системі (наприклад, passenger — легковий)
        vehicleType: "легковий",        // Тип транспортного засобу українською для інтерфейсу (легковий, вантажний тощо)
        hasAdBlue: false,               // Наявність системи очищення вихлопних газів AdBlue (true / false)
        isMiles: false,                 // Чи вимірюється пробіг у милях (true) чи в кілометрах (false)
        formulas: [1, 2, 3, 4]          // Масив номерів формул розрахунку витрати палива для цього типу техніки
    },
    {
        id: 2,
        plate: "АІ 100 G",
        model: "Renault D14 HIGH P4*4 280 E3",
        subdivision: "РМТЗ",
        consumption: 25.0,
        fuelType: "ДП",
        note: "Резерв",
        vin: "WV1ZZZ7HZ5H123456",
        year: 2005,
        transmission: "механіка",
        tankCapacity: 80,
        drive: "передній",
        emptyWeight: 1915,
        totalWeight: 2800,
        gears: 6,
        engineVolume: 2461,
        kw: 96,
        engineNo: "AXD123",
        driver: "Іванов І.І.",
        category: "truck",
        vehicleType: "вантажний",
        hasAdBlue: false,
        isMiles: false,
        formulas: [5, 2, 3, 6]
    },
    {
        id: 3,
        plate: "КІ 102 G",
        model: "MAN TGM13.320 ВВ СН 4*4",
        subdivision: "РМТЗ",
        consumption: 21.5,
        fuelType: "ДП",
        note: "Вантажний з AdBlue",
        vin: "1J8G2E8A54Y140225",
        year: 2004,
        transmission: "автомат",
        tankCapacity: 78,
        drive: "повний",
        emptyWeight: 2260,
        totalWeight: 2750,
        gears: 5,
        engineVolume: 2987,
        kw: 160,
        engineNo: "—",
        driver: "Водій / Старший водій",
        category: "truck",
        vehicleType: "вантажний",
        hasAdBlue: true,
        isMiles: false,
        formulas: [5, 1, 2, 3, 6, 7]
    },
    {
        id: 4,
        plate: "КІ 103 G",
        model: "Ford Explorer (US)",
        subdivision: "РМТЗ",
        consumption: 14.0,
        fuelType: "АБ",
        note: "Американська версія (милі)",
        vin: "1FM5K8F8LGA123789",
        year: 2016,
        transmission: "автомат",
        tankCapacity: 70,
        drive: "повний",
        emptyWeight: 2100,
        totalWeight: 2850,
        gears: 6,
        engineVolume: 3496,
        kw: 213,
        engineNo: "US35V6",
        driver: "Коваленко К.К.",
        category: "miles",
        vehicleType: "легковий",
        hasAdBlue: false,
        isMiles: true,
        formulas: [1, 2, 3, 4]
    },
    {
        id: 5,
        plate: "КІ 104 G",
        model: "TOYOTA LAND CRUISER",
        subdivision: "БПЛА",
        consumption: 12.5,
        fuelType: "АБ",
        note: "Штабний з AdBlue",
        vin: "JTEBZ22J30K987654",
        year: 2021,
        transmission: "автомат",
        tankCapacity: 93,
        drive: "повний",
        emptyWeight: 2450,
        totalWeight: 3260,
        gears: 6,
        engineVolume: 3346,
        kw: 227,
        engineNo: "F33A-FTV",
        driver: "Петров П.П.",
        category: "adblue",
        vehicleType: "легковий",
        hasAdBlue: true,
        isMiles: false,
        formulas: [1, 2, 3, 4]
    },
    {
        id: 6,
        plate: "КІ 105 G",
        model: "Ford Explorer (US)",
        subdivision: "БПЛА",
        consumption: 14.0,
        fuelType: "АБ",
        note: "Американська версія (милі)",
        vin: "1FM5K8F8LGA123456",
        year: 2016,
        transmission: "автомат",
        tankCapacity: 70,
        drive: "повний",
        emptyWeight: 2100,
        totalWeight: 2850,
        gears: 6,
        engineVolume: 3496,
        kw: 213,
        engineNo: "US35V6",
        driver: "Мельник М.М.",
        category: "miles",
        vehicleType: "легковий",
        hasAdBlue: false,
        isMiles: true,
        formulas: [1, 2, 3, 4]
    },
    {
        id: 7,
        plate: "КІ 106 G",
        model: "Toyota Camry",
        subdivision: "БПЛА",
        consumption: 8.5,
        fuelType: "АБ",
        note: "Штабний",
        vin: "4T1B11HK5JU987654",
        year: 2020,
        transmission: "автомат",
        tankCapacity: 60,
        drive: "передній",
        emptyWeight: 1550,
        totalWeight: 2100,
        gears: 8,
        engineVolume: 2487,
        kw: 151,
        engineNo: "A25AFKS",
        driver: "Командувач",
        category: "hq",
        vehicleType: "легковий",
        hasAdBlue: false,
        isMiles: false,
        formulas: [1, 2, 3, 4]
    },
    {
        id: 8,
        plate: "КІ 107 G",
        model: "MAN TGS (Евакуатор)",
        subdivision: "ВТО",
        consumption: 25.0,
        fuelType: "ДП",
        note: "Спецтехніка важка",
        vin: "WMA13XZZ5MW123456",
        year: 2019,
        transmission: "механіка",
        tankCapacity: 300,
        drive: "повний",
        emptyWeight: 11000,
        totalWeight: 26000,
        gears: 16,
        engineVolume: 12419,
        kw: 353,
        engineNo: "D2676LF",
        driver: "Технік Т.Т.",
        category: "special",
        vehicleType: "вантажний",
        hasAdBlue: true,
        isMiles: false,
        formulas: [5, 1, 2, 3, 6, 7]
    },
    {
        id: 9,
        plate: "ТІ 102 G",
        model: "MAN TGM13.320 ВВ СН 4*4",
        subdivision: "ВТО",
        consumption: 21.5,
        fuelType: "ДП",
        note: "Вантажний з AdBlue",
        vin: "1J8G2E8A54Y140225",
        year: 2004,
        transmission: "автомат",
        tankCapacity: 78,
        drive: "повний",
        emptyWeight: 2260,
        totalWeight: 2750,
        gears: 5,
        engineVolume: 2987,
        kw: 160,
        engineNo: "—",
        driver: "Водій / Старший водій",
        category: "truck",
        vehicleType: "вантажний",
        hasAdBlue: true,
        isMiles: false,
        formulas: [5, 1, 2, 3, 6, 7]
    },
    {
        id: 10,
        plate: "ТІ 254 G",
        model: "Suzuki GSX250R",
        subdivision: "РМТЗ",
        consumption: 3.5,
        fuelType: "ДП",
        note: "",
        vin: "WMA13XZZ5",
        year: 2020,
        transmission: "автомат",
        tankCapacity: 15,
        drive: "задній",
        emptyWeight: 178,
        totalWeight: 250,
        gears: 6,
        engineVolume: 248,
        kw: 40,
        engineNo: "12452",
        driver: "водій",
        category: "motorcycle",
        vehicleType: "мотоцикл",
        hasAdBlue: false,
        isMiles: false,
        formulas: [1, 2, 3, 4]
    },
    {
        id: 11,
        plate: "ТІ 255 G",
        model: "CFORCE 1000 MV",
        subdivision: "РМТЗ",
        consumption: 9.0,
        fuelType: "ДП",
        note: "",
        vin: "WMA13XZZ5",
        year: 2020,
        transmission: "автомат",
        tankCapacity: 15,
        drive: "задній",
        emptyWeight: 178,
        totalWeight: 250,
        gears: 6,
        engineVolume: 248,
        kw: 40,
        engineNo: "12452",
        driver: "водій",
        category: "quad",
        vehicleType: "квадроцикл",
        hasAdBlue: false,
        isMiles: false,
        formulas: [1, 2, 3, 4]
    }
];

function saveCarsToStorage() {}